import { Book } from '../../models/book.interface';

export const BOOKS_DATA: Book[] = [
  {
    title: 'The Midnight Library',
    author: 'Matt Haig',
    genre: 'Fiction',
    price: 24.99,
    availability: true,
    rating: 4.5,
    publishDate: '2020-08-13',
  },
  {
    title: 'Dune',
    author: 'Frank Herbert',
    genre: 'Science Fiction',
    price: 19.99,
    availability: true,
    rating: 4.8,
    publishDate: '1965-08-01',
  },
  {
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    genre: 'Science Fiction',
    price: 27.99,
    availability: false,
    rating: 4.7,
    publishDate: '2021-05-04',
  },
  {
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    genre: 'Thriller',
    price: 16.99,
    availability: true,
    rating: 4.3,
    publishDate: '2019-02-05',
  },
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    genre: 'Self-Help',
    price: 21.99,
    availability: true,
    rating: 4.9,
    publishDate: '2018-10-16',
  },
  {
    title: 'The Thursday Murder Club',
    author: 'Richard Osman',
    genre: 'Mystery',
    price: 18.99,
    availability: true,
    rating: 4.2,
    publishDate: '2020-09-03',
  },
  {
    title: 'Where the Crawdads Sing',
    author: 'Delia Owens',
    genre: 'Literary Fiction',
    price: 15.99,
    availability: true,
    rating: 4.6,
    publishDate: '2018-08-14',
  },
  {
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    genre: 'Finance',
    price: 23.99,
    availability: false,
    rating: 4.7,
    publishDate: '2020-09-08',
  },
];
